(define (make-account balance account-password)
    (define failed-access-attempts 0)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                   balance)
            "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount))
        balance)
    (define (call-the-cops x)
        "Dialing 911...")
    (define (incorrect-password x)
        "Incorrect password")
    (define (dispatch given-password m)
        (if (eq? given-password account-password)
            (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (error "Unknown request: MAKE-ACCOUNT"
                            m)))
            (begin (set! failed-access-attempts (+ 1 failed-access-attempts))
                    (if (> failed-access-attempts 7)
                        call-the-cops
                        incorrect-password))))
    dispatch)

(define acc (make-account 100 'secret-password))
(display ((acc 'secret-password 'withdraw) 40)) (newline)
(display ((acc 'some-other-password 'deposit) 50)) (newline)
(display ((acc 'some-other-password 'deposit) 50)) (newline)
(display ((acc 'some-other-password 'deposit) 50)) (newline)
(display ((acc 'some-other-password 'deposit) 50)) (newline)
(display ((acc 'some-other-password 'deposit) 50)) (newline)
(display ((acc 'some-other-password 'deposit) 50)) (newline)
(display ((acc 'some-other-password 'deposit) 50)) (newline)
(display ((acc 'some-other-password 'deposit) 50)) (newline)