(define (lookup given-key set-of-records)
    (let ((this-key (key (car set-of-records))))
        (cond ((null? set-of-records) false)
            ((= given-key this-key)
                (car set-of-records))
            ((< given-key this-key)
                (lookup given-key (left-branch set-of-records)))
            ((> given-key this-key)
                (lookup given-key (right-branch set-of-records))))))