(define (install-=zero?)
    (define (rat-is-zero? x)
        (equ? x (make-rational 0 1)))
    (define (complex-is-zero? x)
        (equ? x (make-complex-from-real-imag 0 0)))
    (put '=zero? 'scheme-number (lambda (x) (= x 0)))
    (put '=zero? 'rational rat-is-zero?)
    (put '=zero? 'complex complex-is-zero?)
    'done)